[workspace]

members = [
  "workers/inventory",
  "workers/manufacturing",
  "workers/material",
  "workers/order",
  "workers/product",
  "workers/routing",
]

resolver = "2"

[profile.release]
lto = true
opt-level = 's'
