package stan:material

interface api {
  type id = u64;

  record material {
    id: id,
    name: string,
  }

  record material-add {
    name: string,
    // ... remaining
  }

  enum error-add {
    max-capacity,
  }

  /// get material
  get: func(id: id) -> option<material>

  /// add material
  /// returns material id or error
  add: func(material: material-add) -> result<id, error-add>
}

world material {
  export api
}