package golem:order

interface api {
  record item {
    product-id: string,
    price: float32,
    quantity: u32,
  }

  enum error {
    inventory-too-low,
    payment-declined
    // todo: ...
  }

  record payment {
    handler: func(amount: float32) -> result<_, error-payment>
  }

  enum error-payment {
    declined
    // todo: ...
  }

  create: func(item: item, payment: payment) -> result<_, error>
}

world order {
  import golem:inventory/api

  export api
}
