package stan:order

interface api {
  use stan:customer/api.{customer}
  use stan:inventory/api.{amount}

  record item {
    product-id: u64,
    price: float32,
    quantity: amount,
  }

  enum error {
    declined,
    inventory-too-low,
    // todo: ...
  }

  create: func(item: item, customer: customer) -> result<_, error>
}

world order {
  import stan:inventory/api

  export api
}
