package golem:order

interface api {
  record item {
    product-id: string,
    price: float32,
    quantity: u32,
  }

  enum error {
    inventory-too-low,
    // todo: ...
  }

  create: func(item: item) -> result<_, error>
}

world order {
  import golem:inventory/api

  export api
}
