package golem:template

interface api {
  record material {
    id: u64,
    name: string,
  }

  record material-add {
    name: string,
    // ... remaining
  }

  enum error-add {
    max-capacity,
  }

  /// get material
  get: func(id: u64) -> option<material>

  /// add material
  /// returns material id or error
  add: func(material: material-add) -> result<u64, error-add>
}

world material {
  export api
}