package golem:template

interface api {
  record material {
    name: string,
  }

  enum error {
    duplicate,
    // todo: ...
  }

  /// get material
  get: func(id: string) -> option<material>

  /// add material
  /// returns material id or error
  add: func(material: material) -> result<string, error>
}

world material {
  export api
}