package golem:product

interface api {
  record product {
    id: string,
    name: string,
  }

  enum error {
    duplicate,
    // todo: ...
  }

  get: func(id: string) -> option<product>

  add: func(product: product) -> result<_, error>
}

world product {
  export api
}