[package]
name = "manufacturing"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
cargo-component-bindings = "0.4.1"

[package.metadata.component]
package = "golem:manufacturing"

[package.metadata.component.target.dependencies]
