package stan:inventory

interface api {
  type id = u64;
  type amount = u32;

  enum error-increase {
    too-high,
    // todo: ...
  }

  enum error-decrease {
    too-low,
    // todo: ...
  }

  /// get inventory
  get: func(id: id) -> amount

  /// increase inventory
  /// returns new amount or error
  increase: func(id: id, amount: amount) -> result<_, error-increase>
  
  /// decrease inventory
  /// returns new amount or error
  decrease: func(id: id, amount: amount) -> result<_, error-decrease>
}

world inventory {
  export api
}